services:
    fastapi:
        container_name: alghoritm_back
        build:
            context: ../backend
            dockerfile: Dockerfile
        ports:
            - "5678:5678"
            - "3415:3415"
        command: "debugpy --listen 0.0.0.0:5678 -m uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 3415"
        volumes:
            - ../backend:/backend
        networks:
            - alghoritm

networks:
    alghoritm:
        driver: bridge
