services:
    fastapi:
        container_name: alghoritm_back
        build:
            context: ../backend
            dockerfile: Dockerfile
        ports:
            - "3415:3415"
        command: "uvicorn --factory src.main:create_app --host 0.0.0.0 --port 3415 --workers 3"
        networks:
            - alghoritm

networks:
    alghoritm:
        driver: bridge
