services:
    frontend:
        container_name: alghoritm_front
        build:
            context: ../frontend
            dockerfile: Dockerfile
        ports:
            - "3410:3410"
        command: /bin/sh -c "pnpm run dev --host --port=3410"
        volumes:
            - ../frontend:/frontend
        networks:
            - alghoritm

networks:
    alghoritm:
        driver: bridge
