services:
    frontend:
        container_name: alghoritm_front
        build:
            context: ../frontend
            dockerfile: Dockerfile
        ports:
            - "3410:3410"
        command: /bin/sh -c "pnpm build && pnpm preview --host --port 3410"
        networks:
            - alghoritm

networks:
    alghoritm:
        driver: bridge
